exclude-newer = "7 days"
exclude-newer-package = { pyrefly = false }

[project]
name = "bandcamp-downloader"
authors = [
  { name = "Iheanyi Ekechukwu", email = "iekechukwu@gmail.com" },
  { name = "Anthony Forsberg", email = "forsberganthony@yahoo.com" },
]
version = "0.0.18"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.15"
classifiers = [
  'Development Status :: 4 - Beta',
  'Intended Audience :: End Users/Desktop',
  'Topic :: Multimedia :: Sound/Audio',
  'Programming Language :: Python :: 3.10',
]
dependencies = [
  "beautifulsoup4 >= 4.13.0b2",
  "demjson3 >= 3.0.6",
  "mutagen >= 1.47.0",
  "pydantic>=2.10.6",
  "requests >= 2.32.3",
  "toml>=0.10.2",
  "typed-argparse>=0.3.1",
  "unicode-slugify>=0.1.5",
  "urllib3 >= 2.2.2",
]

license = "Unlicense"
license-files = ["UNLICENSE"]

[dependency-groups]
dev = [
  "pyrefly>=1.2.0",
  "ruff>=0.14.14",
  "types-requests>=2.32.0.20241016",
  "types-toml>=0.10.8.20240310",
]


[project.scripts]
bandcamp-dl = "bandcamp_dl.main:main"

[build-system]
requires = ["uv_build~=0.12.3"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "bandcamp_dl"
module-root = ""

[tool.uv.sources]
unicode-slugify = { git = "https://github.com/dnicolson/unicode-slugify.git", rev = "a18826f" }

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  "E",    # pycodestyle
  "W505", # Docstring line too long
  "F",    # Pyflakes
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
  "SIM",  # flake8-simplify
  "I",    # isort
  "ISC",  # implicit string concat
  "PT",   # pytest
  "RET",  # return
  "ERA",  # remove commented code
  "PGH",  # use specific error code for lint ignores
  "PL",   # pylint
  "PERF",
  "FURB",
  "A005",
]
ignore = [
  "E501",   # Line too long
  "ISC001",
  "PLR091", # Uncle Bob's BS
  "PTH123", # open should be replaced by Path.open
]


[tool.pyrefly]
use-ignore-files = false
enabled-ignores = ["type", "pyrefly", "ty"]
output-format = "min-text"
min-severity = "warn"
preset = 'strict'

[tool.pyrefly.errors]
unannotated-return = true
invalid-abstract-method = true
unused-call-result = true
empty-body = true
missing-super-call = true
unsupported-dynamic-base = true
implicit-reexport = true
unknown-argument-type = true
unknown-attribute-type = true
implicit-any-lambda = true
untyped-function-decorator = true
untyped-class-decorator = true
unused-type-ignore = true
no-any-return = true
untyped-import = true
open-unpacking = true
not-required-key-access = true
implicitly-defined-attribute = true
implicit-any = true
implicit-bool = true
invalid-cast = true
